blank_issues_enabled: false

contact_links:
  - name: 💬 Soporte general / Preguntas
    url: https://github.com/TU_ORGANIZACION_O_REPO/discussions
    about: Si tienes dudas generales, sugerencias o necesitas ayuda, por favor abre un hilo de discusión.
