# ------------------------------------------------------------------------------
# ARCHIVO: hpa.yaml
# DESCRIPCIÓN: Este manifiesto crea un HorizontalPodAutoscaler (HPA) en Kubernetes
#              que escala automáticamente el número de réplicas del deployment
#              `nginx-basic` basado en la utilización promedio de CPU.
#
# AUTOR: Alejandro Castro Martínez
# FECHA DE MODIFICACIÓN: 27 de marzo de 2025
# CONTEXTO:
#   - Utilizado en el experimento `exp1_basic-autoscaling` para observar la
#     respuesta del sistema ante cargas variables.
#   - El HPA monitorea el uso de CPU de los pods y ajusta su cantidad según
#     la configuración establecida.
#   - Compatible con métricas del recurso CPU definidas en el deployment asociado.
# ------------------------------------------------------------------------------

# ---------------------------------------------------------------
# DEFINICIÓN DEL OBJETO: HorizontalPodAutoscaler (v2 API)
# ---------------------------------------------------------------
apiVersion: autoscaling/v2  # Versión avanzada que permite más tipos de métricas
kind: HorizontalPodAutoscaler

# ---------------------------------------------------------------
# METADATOS DE IDENTIFICACIÓN
# ---------------------------------------------------------------
metadata:
  name: nginx-basic-hpa            # Nombre único del objeto HPA
  labels:
    app: nginx-basic               # Etiqueta para trazabilidad

# ---------------------------------------------------------------
# ESPECIFICACIONES DEL ESCALADOR
# ---------------------------------------------------------------
spec:
  # Referencia directa al Deployment que se desea escalar
  scaleTargetRef:
    apiVersion: apps/v1            # API del objeto destino (Deployment)
    kind: Deployment               # Tipo del objeto a escalar
    name: nginx-basic              # Nombre exacto del Deployment objetivo

  # ---------------------------------------------------------------
  # RANGO DE ESCALADO PERMITIDO
  # ---------------------------------------------------------------
  minReplicas: 1                   # Límite inferior (siempre al menos 1 pod activo)
  maxReplicas: 10                  # Límite superior (no escalará por encima de 10 pods)

  # ---------------------------------------------------------------
  # MÉTRICA DE ESCALADO: Utilización promedio del recurso CPU
  # ---------------------------------------------------------------
  metrics:
    - type: Resource               # Tipo de métrica basada en recursos del sistema
      resource:
        name: cpu                 # Se monitoriza el uso de CPU
        target:
          type: Utilization       # Objetivo definido como porcentaje de uso
          averageUtilization: 25  # Si el uso promedio supera 25%, se activa el escalado
