apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true      
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # Definición de recursos (crucial para que HPA pueda calcular uso relativo)
        resources:
          requests:
            cpu: 100m         # Solicitud mínima de CPU (0.1 core)
            memory: 64Mi      # Solicitud mínima de memoria
          limits:
            cpu: 500m         # Límite máximo de CPU permitido (0.5 core)
            memory: 128Mi     # Límite máximo de memoria
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
