apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  namespace: elasticity-m2
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile      on;
      keepalive_timeout  65;

      # DNS interno de Kubernetes usando IP directa
      resolver 10.96.0.10 valid=30s;

      server {
        listen 80;

        location /compute {
          proxy_pass         http://service-s0.elasticity-m2.svc.cluster.local:5000/compute$is_args$args;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_connect_timeout 5s;
          proxy_read_timeout 10s;
          proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        }
      }
    }
